// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Namerd.Persistence.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Namerd.Migrations
{
    [DbContext(typeof(NamerdContext))]
    partial class NamerdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Namerd.Domain.MonthlyNomination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsNominationActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("botId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("botId");

                    b.ToTable("MonthlyNominations");
                });

            modelBuilder.Entity("Namerd.Domain.NamerdBot", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("SettingsId")
                        .HasColumnType("integer");

                    b.HasKey("GuildId");

                    b.HasIndex("SettingsId");

                    b.ToTable("Bots");
                });

            modelBuilder.Entity("Namerd.Domain.NominationDetails", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<int?>("MonthlyNominationId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("MonthlyNominationId");

                    b.ToTable("NominationDetails");
                });

            modelBuilder.Entity("Namerd.Domain.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("NominateChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Namerd.Domain.MonthlyNomination", b =>
                {
                    b.HasOne("Namerd.Domain.NamerdBot", "bot")
                        .WithMany("MonthlyNomination")
                        .HasForeignKey("botId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bot");
                });

            modelBuilder.Entity("Namerd.Domain.NamerdBot", b =>
                {
                    b.HasOne("Namerd.Domain.Settings", "Settings")
                        .WithMany()
                        .HasForeignKey("SettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("Namerd.Domain.NominationDetails", b =>
                {
                    b.HasOne("Namerd.Domain.MonthlyNomination", null)
                        .WithMany("NominationDetails")
                        .HasForeignKey("MonthlyNominationId");
                });

            modelBuilder.Entity("Namerd.Domain.MonthlyNomination", b =>
                {
                    b.Navigation("NominationDetails");
                });

            modelBuilder.Entity("Namerd.Domain.NamerdBot", b =>
                {
                    b.Navigation("MonthlyNomination");
                });
#pragma warning restore 612, 618
        }
    }
}
